### ISSUE TITLE
Test TallyVotes.test.ts fails

### ISSUE THREAD

**Issue by Subway2023** [privacy-scaling-explorations/maci#1839]
## Steps to Reproduce

```
cd circuits
npm install
npx jest __tests__/TallyVotes.test.ts
```
## Failure Logs
```

    /mnt/sdd1/sbw/circom/ZKAP_docker/sbwTest/benchmarks/maci-4892ada0dc7bcc2f7710aea917e309f1553317c5/circuits/node_modules/@zk-kit/poseidon-cipher/dist/index.js:9
    import { Fr, r } from '@zk-kit/baby-jubjub';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1350:14)
      at Object.<anonymous> (node_modules/maci-crypto/ts/hashing.ts:1:1)
```

**Comment by ctrlc03** [comment]
> ## Steps to Reproduce
> ```
> cd circuits
> npm install
> npx jest __tests__/TallyVotes.test.ts
> ```
> 
> ## Failure Logs
> ```
> 
>     /mnt/sdd1/sbw/circom/ZKAP_docker/sbwTest/benchmarks/maci-4892ada0dc7bcc2f7710aea917e309f1553317c5/circuits/node_modules/@zk-kit/poseidon-cipher/dist/index.js:9
>     import { Fr, r } from '@zk-kit/baby-jubjub';
>     ^^^^^^
> 
>     SyntaxError: Cannot use import statement outside a module
> 
>       at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1350:14)
>       at Object.<anonymous> (node_modules/maci-crypto/ts/hashing.ts:1:1)
> ```

So those tests are not meant to be run with Jest, you can run that particular one using `pnpm test:tallyVotes` - lmk if that works @Subway2023

**Comment by Subway2023** [comment]
> > ## Steps to Reproduce
> > ```
> > cd circuits
> > npm install
> > npx jest __tests__/TallyVotes.test.ts
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ## Failure Logs
> > ```
> > 
> >     /mnt/sdd1/sbw/circom/ZKAP_docker/sbwTest/benchmarks/maci-4892ada0dc7bcc2f7710aea917e309f1553317c5/circuits/node_modules/@zk-kit/poseidon-cipher/dist/index.js:9
> >     import { Fr, r } from '@zk-kit/baby-jubjub';
> >     ^^^^^^
> > 
> >     SyntaxError: Cannot use import statement outside a module
> > 
> >       at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1350:14)
> >       at Object.<anonymous> (node_modules/maci-crypto/ts/hashing.ts:1:1)
> > ```
> 
> So those tests are not meant to be run with Jest, you can run that particular one using `pnpm test:tallyVotes` - lmk if that works @Subway2023
> 
> Also make sure you are using `pnpm` and installing and building before running tests. In the monorepo root: `pnpm install && pnpm build`

According to your method, I still cannot run it, and the above error persists. I am running an  [older version](https://github.com/privacy-scaling-explorations/maci/commit/4bc217db24f573c1da5e24ad0caca596637c3dc8) of the project, which has a bug:  [Initial Conditions Are Not Properly Enforced](https://github.com/nullity00/zk-security-reviews/blob/main/MACI/20210922%20Hashcloak%20audit%20report.pdf) so I want to conduct tests. The old version includes a jest.config.js file, so I suspect it uses the Jest framework. However, I still haven't successfully run TallyVotes.test.ts.

**Comment by ctrlc03** [comment]
> > > ## Steps to Reproduce
> > > ```
> > > cd circuits
> > > npm install
> > > npx jest __tests__/TallyVotes.test.ts
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ## Failure Logs
> > > ```
> > > 
> > >     /mnt/sdd1/sbw/circom/ZKAP_docker/sbwTest/benchmarks/maci-4892ada0dc7bcc2f7710aea917e309f1553317c5/circuits/node_modules/@zk-kit/poseidon-cipher/dist/index.js:9
> > >     import { Fr, r } from '@zk-kit/baby-jubjub';
> > >     ^^^^^^
> > > 
> > >     SyntaxError: Cannot use import statement outside a module
> > > 
> > >       at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1350:14)
> > >       at Object.<anonymous> (node_modules/maci-crypto/ts/hashing.ts:1:1)
> > > ```
> > 
> > 
> > So those tests are not meant to be run with Jest, you can run that particular one using `pnpm test:tallyVotes` - lmk if that works @Subway2023
> > Also make sure you are using `pnpm` and installing and building before running tests. In the monorepo root: `pnpm install && pnpm build`
> 
> According to your method, I still cannot run it, and the above error persists. I am running an [older version](https://github.com/privacy-scaling-explorations/maci/commit/4bc217db24f573c1da5e24ad0caca596637c3dc8) of the project, which has a bug: [Initial Conditions Are Not Properly Enforced](https://github.com/nullity00/zk-security-reviews/blob/main/MACI/20210922%20Hashcloak%20audit%20report.pdf) so I want to conduct tests. The old version includes a jest.config.js file, so I suspect it uses the Jest framework. However, I still haven't successfully run TallyVotes.test.ts.

@Subway2023 I see, but based on the stack trace it doesn't look like you are running that old version, at the time the project was not using `@zk-kit/baby-jubjub` so it could not error out there. Could you share the full instructions on how to reproduce it please?

**Comment by Subway2023** [comment]
```
cd circuits
npm install

npx jest TallyVotes.test.ts
```

<img width="609" alt="1727767797569" src="https://github.com/user-attachments/assets/994a2b01-d78a-4813-893a-9d987070e6ba">

commad (npx jest TallyVotes.test.ts) comes from the testing program in the project.

**Comment by ctrlc03** [comment]
> ```
> cd circuits
> npm install
> 
> npx jest TallyVotes.test.ts
> ```
> 
> <img alt="1727767797569" width="609" src="https://private-user-images.githubusercontent.com/147013944/372362406-994a2b01-d78a-4813-893a-9d987070e6ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3NjgyODEsIm5iZiI6MTcyNzc2Nzk4MSwicGF0aCI6Ii8xNDcwMTM5NDQvMzcyMzYyNDA2LTk5NGEyYjAxLWQ3OGEtNDgxMy04OTNhLTlkOTg3MDcwZTZiYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMVQwNzMzMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYzBjYWYzMjhlNDA3NjE5ZWViMGU3ODY0MWE1MWRmZDljZWIyZTFiM2EyMzBlNThhY2E4YzA1ZjE5ZDVjZGIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3SeS36QLCTIKRMucX8u5KJa2YExBDDR0x_IcJu2v5dM">
> commad (npx jest TallyVotes.test.ts) comes from the testing program in the project.

Let's take a step back, did you clone the repo and checked out to a specific commit, a pr? did you install the package from npm? Knowing that would allow me to try it out too

**Comment by Subway2023** [comment]
i just download this [commit](https://github.com/privacy-scaling-explorations/maci/tree/4bc217db24f573c1da5e24ad0caca596637c3dc8) and perform above commands.

**Comment by ctrlc03** [comment]
> i just download this [commit](https://github.com/privacy-scaling-explorations/maci/tree/4bc217db24f573c1da5e24ad0caca596637c3dc8) and perform above commands.

ok so first you need to install the packages and build the monorepo. Also you'd need to install these libraries https://github.com/privacy-scaling-explorations/maci/blob/4bc217db24f573c1da5e24ad0caca596637c3dc8/.travis.yml#L7

You can see the steps required to make that specific version working in this file https://github.com/privacy-scaling-explorations/maci/blob/4bc217db24f573c1da5e24ad0caca596637c3dc8/.travis.yml

You can https://github.com/privacy-scaling-explorations/maci/blob/4bc217db24f573c1da5e24ad0caca596637c3dc8/.travis.yml#L11-L14
Then https://github.com/privacy-scaling-explorations/maci/blob/4bc217db24f573c1da5e24ad0caca596637c3dc8/circuits/scripts/runTestsInCi.sh#L6
Then ( no need for && ofc) https://github.com/privacy-scaling-explorations/maci/blob/4bc217db24f573c1da5e24ad0caca596637c3dc8/circuits/scripts/runTestsInCi.sh#L10

**Comment by Subway2023** [comment]
my commands are as follows:
```
npm i 
npm run bootstrap 
npm run build 
cd circuits
npm i

npm run circom-helper & npx jest TallyVotes.test.ts
```
however there is still errors:
```
    /mnt/sdd1/sbw/circom/ZKAP_docker/sbwTest/benchmarks/maci-4bc217db24f573c1da5e24ad0caca596637c3dc8/circuits/node_modules/@zk-kit/poseidon-cipher/dist/index.js:9
    import { Fr, r } from '@zk-kit/baby-jubjub';
    ^^^^^^
```

**Comment by Subway2023** [comment]
Thank you very much! it works.

**Comment by Subway2023** [comment]
Why can't TallyVotes.test.ts pass the tests? 
```
npx jest TallyVotes.test.ts

 FAIL  ts/__tests__/TallyVotes.test.ts (15.032 s)
  TallyVotes circuit
    1 user, 2 messages
      ✕ should produce the correct result commitments (4263 ms)
    10 users, 10 messages
      ✕ should produce the correct state root and ballot root (8029 ms)

  ● TallyVotes circuit › 1 user, 2 messages › should produce the correct result commitments

    Request failed with status code 503
```

However, if I get the generatedInputs from TallyVotes.test.ts, generate the witness, and perform the checks, it works successfully. [Test](https://github.com/Subway2023/zkbugs/blob/main/dataset/circom/maci/4bc21_initial_conditionsa_are_not_properly_enforced/zkbugs_positive_test.sh) is my test script

**Comment by ctrlc03** [comment]
> Why can't TallyVotes.test.ts pass the tests?
> 
> ```
> npx jest TallyVotes.test.ts
> 
>  FAIL  ts/__tests__/TallyVotes.test.ts (15.032 s)
>   TallyVotes circuit
>     1 user, 2 messages
>       ✕ should produce the correct result commitments (4263 ms)
>     10 users, 10 messages
>       ✕ should produce the correct state root and ballot root (8029 ms)
> 
>   ● TallyVotes circuit › 1 user, 2 messages › should produce the correct result commitments
> 
>     Request failed with status code 503
> ```
> 
> However, if I get the generatedInputs from TallyVotes.test.ts, generate the witness, and perform the checks, it works successfully. [Test](https://github.com/Subway2023/zkbugs/blob/main/dataset/circom/maci/4bc21_initial_conditionsa_are_not_properly_enforced/zkbugs_positive_test.sh) is my test script

hey sorry just getting back to work today, will try and find some time to run through this. have you got any updates on this since 2 weeks ago?

**Comment by Subway2023** [comment]
Thank you for your reply. I currently have no new progress. My goal is to execute TallyVotes.test.ts to obtain the inputs for tallyVotes.circom in order to reproduce the [vulnerability of **Initial Conditions Are Not Properly Enforced**](https://github.com/nullity00/zk-security-reviews/blob/main/MACI/20210922%20Hashcloak%20audit%20report.pdf). Please refer to the [issue](https://github.com/privacy-scaling-explorations/maci/issues/1852). I would greatly appreciate any help you can provide on this matter.

**Comment by ctrlc03** [comment]
Hey sorry to come back to this so late. Have you managed to make any progress?
