### ISSUE TITLE
Error: Too many values for input signal currentStateLeavesPathElements when generating proofs

### ISSUE THREAD

**Issue by lcs86-dev** [privacy-scaling-explorations/maci#1956]
# Error: Too many values for input signal currentStateLeavesPathElements when generating proofs

## Prerequisites
- [x] I am not running a deprecated version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Expected Behavior
After successful poll finalization, running the proof generation command should successfully generate the required proofs.

## Current Behavior
The proof generation fails with an error about too many values for input signal currentStateLeavesPathElements.

### Steps to Reproduce
1. Deploy MACI contracts on Optimism Sepolia testnet with coordinator address: `0xF21Dc41f16885edcA1eB696A0701aA603DF08809`
2. Complete full voting cycle (signup, create applications, vote)  
3. Successfully finalize the poll
4. Run proof generation command:
```bash
pnpm run prove:optimism-sepolia --poll 2 \
   --coordinator-private-key ... \
   --tally-file ../cli/tally.json \
   --output-dir ../cli/proofs/ \
   --start-block 20670230 \
   --blocks-per-batch 50
   
### Error Logs
Error: Too many values for input signal currentStateLeavesPathElements
    at /Users/imchangsu/project/maci/node_modules/.pnpm/circom_runtime@0.1.25/node_modules/circom_runtime/build/main.cjs:493:27
    at Array.forEach (<anonymous>)
    at WitnessCalculatorCircom2._doCalculateWitness (/Users/imchangsu/project/maci/node_modules/.pnpm/circom_runtime@0.1.25/node_modules/circom_runtime/build/main.cjs:477:14)
    at WitnessCalculatorCircom2.calculateWTNSBin (/Users/imchangsu/project/maci/node_modules/.pnpm/circom_runtime@0.1.25/node_modules/circom_runtime/build/main.cjs:536:20)
    at wtnsCalculate (/Users/imchangsu/project/maci/node_modules/.pnpm/snarkjs@0.7.4/node_modules/snarkjs/build/main.cjs:1268:28)
    at async Object.groth16FullProve [as fullProve] (/Users/imchangsu/project/maci/node_modules/.pnpm/snarkjs@0.7.4/node_modules/snarkjs/build/main.cjs:1301:5)
    at async genProof (/Users/imchangsu/project/maci/packages/circuits/build/ts/proofs.js:61:42)
    at async ProofGenerator.generateProofs (/Users/imchangsu/project/maci/packages/contracts/tasks/helpers/ProofGenerator.ts:405:38)
    at async Promise.all (index 0)
    at async ProofGenerator.generateMpProofs (/Users/imchangsu/project/maci/packages/contracts/tasks/helpers/ProofGenerator.ts:223:22)

**Comment by ctrlc03** [comment]
hey @lcs86-dev! The error here is that you deployed the maci contract with the parameter stateTreeDepth set to 14 (I checked here: https://sepolia-optimism.etherscan.io/address/0xd0bd32f180ebfc9eed674a2a5681c9d6b7da937c#readContract) - but I believe you are using test zkey artifacts which use 10 for that argument. Either you download these keys https://maci.pse.dev/docs/getting-started#download-ceremony-artifacts or re-deploy the contracts using these parameters https://github.com/privacy-scaling-explorations/maci/blob/dev/packages/contracts/deploy-config-example.json#L37-L46

**Comment by lcs86-dev** [comment]
> https://maci.pse.dev/docs/getting-started#download-ceremony-artifacts

I appreciate you taking the time to help identify the issue with the stateTreeDepth parameter mismatch.
I'll re-deploy the contracts using the parameters you linked. Thank you!

**Comment by ctrlc03** [comment]
> > https://maci.pse.dev/docs/getting-started#download-ceremony-artifacts
> 
> I appreciate you taking the time to help identify the issue with the stateTreeDepth parameter mismatch. I'll re-deploy the contracts using the parameters you linked. Thank you!

@lcs86-dev  perfect, please let me know if that fixes it so we can mark this as completed.

**Comment by Feelthewind** [comment]
It works perfect! Thanks.

**Comment by lcs86-dev** [comment]
It works perfec! Thanks.

**Comment by ctrlc03** [comment]
Perfect, closing it then! feel free to drop to discord or open another issue if you face any more problems!!
