### ISSUE TITLE
`.zkey` file of TallyVotes(`12-3-5`) has an errors

### ISSUE THREAD

**Issue by gurrpi** [privacy-scaling-explorations/maci#469]
## circuit
name: TallyVotes
circuit source code: https://github.com/privacy-scaling-explorations/maci/blob/v1/circuits/circom/tallyVotes.circom
constrains: 33 M (33265305)
`.zkey` file Download link: https://maci-devops-zkeys.s3.ap-northeast-2.amazonaws.com/TallyVotes_12-3-5_test.0.zkey (32.8 GB, generated using `powersOfTau28_hez_final_26.ptau`)
glibc: 2.11

https://github.com/iden3/circom/tree/new-simplification-heuristics had been used to compile this circuit

##  Contribution failure

`snarkjs contribute` commands fails instantly:
```
$ snarkjs zkey contribute zkeys/TallyVotes_12-3-5_test.0.zkey zkeys/TallyVotes_12-3-5_test.1.zkey --name="paik" -v
[ERROR] snarkJS: Error: zkeys/TallyVotes_12-3-5_test.0.zkey: Missing section 10
    at Object.startReadUniqueSection (/home/ubuntu/.nvm/versions/node/v16.15.1/lib/node_modules/snarkjs/node_modules/@iden3/binfileutils/build/main.cjs:96:38)
    at readMPCParams (/home/ubuntu/.nvm/versions/node/v16.15.1/lib/node_modules/snarkjs/build/cli.cjs:3971:35)
    at phase2contribute (/home/ubuntu/.nvm/versions/node/v16.15.1/lib/node_modules/snarkjs/build/cli.cjs:4867:29)
    at async clProcessor (/home/ubuntu/.nvm/versions/node/v16.15.1/lib/node_modules/snarkjs/build/cli.cjs:305:27)
```

### `snarkjs prove` command failure

```
$ snarkjs groth16 prove ./zkeys/TallyVotes_12-3-5_test.0.zkey /tmp/tmp-5853-KVC2HefSn10Z/output.wtns /tmp/tmp-5853-KVC2HefSn10Z/proof.json /tmp/tmp-5853-KVC2HefSn10Z/public.json
[ERROR] snarkJS: TypeError: Cannot read properties of undefined (reading '0')
    at Object.readSection (/home/ubuntu/.nvm/versions/node/v16.15.0/lib/node_modules/snarkjs/node_modules/@iden3/binfileutils/build/main.cjs:143:67)
    at groth16Prove$1 (/home/ubuntu/.nvm/versions/node/v16.15.0/lib/node_modules/snarkjs/build/cli.cjs:5550:54)
    at async Object.groth16Prove [as action] (/home/ubuntu/.nvm/versions/node/v16.15.0/lib/node_modules/snarkjs/build/cli.cjs:8337:36)
    at async clProcessor (/home/ubuntu/.nvm/versions/node/v16.15.0/lib/node_modules/snarkjs/build/cli.cjs:304:27
```

### `strace` of rapidsnark
```
openat(AT_FDCWD, "./zkeys/TallyVotes_12-3-5_test.0.zkey", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0664, st_size=35231445460, ...}) = 0
mmap(NULL, 35231445460, PROT_READ, MAP_PRIVATE|MAP_POPULATE, 3, 0) = 0x7f782e21d000
mmap(NULL, 35231449088, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f6ffa2c9000
munmap(0x7f782e21d000, 35231445460)     = 0
close(3)                                = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SI_KERNEL, si_addr=NULL} ---
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault (core dumped)
```

#### Environment
OS: Ubuntu 20.04
Node.js: v16.15.1
snarkjs: `0.4.22`

**Comment by gurrpi** [comment]
Filed an issue to `snarkjs` repo: https://github.com/iden3/snarkjs/issues/183

**Comment by gurrpi** [comment]
Regenerated one works fine. So closing this issue.

#### Regeneration detail
Used x2iedn.8xlarge (32 vCPUs, 1,024 GB memory) and took 9 hours, file size is 42 G 
.zkey file link: https://maci-develop-fra.s3.eu-central-1.amazonaws.com/TallyVotes_12-3-5_test.0.zkey
OS tweaked and patched Node.js by following instructions: https://github.com/hermeznetwork/phase2ceremony_4/blob/main/VERIFY.md
