### ISSUE TITLE
circuits unit test failure

### ISSUE THREAD

**Issue by chaosma** [privacy-scaling-explorations/maci#538]
```
cd maci/circuits
# in one terminal run:
npm run circom-helper 
# in second terminal run:
npm run test-processMessages

```
 Add debug info into circom-helper giving results look like:

```
● ProcessMessage circuit › 1 user, key-change › should produce the correct state root and ballot root

    Wrong number of inputs, expectedNumInputs=557, numInputs=787

      at node_modules/circom-helper/ts/utils.ts:34:15
      at step (node_modules/circom-helper/build/utils.js:33:23)
      at Object.next (node_modules/circom-helper/build/utils.js:14:53)
      at fulfilled (node_modules/circom-helper/build/utils.js:5:58)
```

The error is caused by mis-match circuit inputs generation.

**Comment by gurrpi** [comment]
## Error log

```
npm run test-processMessages

> maci-circuits@1.1.0 test-processMessages
> NODE_OPTIONS=--max-old-space-size=4096 jest ts/__tests__/ProcessMessages.test.ts

  console.log
    Signing up with 14434780084084022819484116535012917159963211897268354077703959798202097973505n

      at ts/__tests__/ProcessMessages.test.ts:366:21

 FAIL  ts/__tests__/ProcessMessages.test.ts (10.409 s)
  ProcessMessage circuit
    1 user, 2 messages
      ✕ should produce the correct state root and ballot root (803 ms)
    2 users, 1 message
      ✕ should produce the correct state root and ballot root (515 ms)
    1 user, key-change
      ✕ should produce the correct state root and ballot root (864 ms)
    1 user, 10 messages
      ✕ should produce the correct state root and ballot root (3622 ms)

  ● ProcessMessage circuit › 1 user, 2 messages › should produce the correct state root and ballot root

    Wrong number of inputs

      at node_modules/circom-helper/ts/utils.ts:34:15
      at step (node_modules/circom-helper/build/utils.js:33:23)
      at Object.next (node_modules/circom-helper/build/utils.js:14:53)
      at fulfilled (node_modules/circom-helper/build/utils.js:5:58)

  ● ProcessMessage circuit › 2 users, 1 message › should produce the correct state root and ballot root

    Wrong number of inputs

      at node_modules/circom-helper/ts/utils.ts:34:15
      at step (node_modules/circom-helper/build/utils.js:33:23)
      at Object.next (node_modules/circom-helper/build/utils.js:14:53)
      at fulfilled (node_modules/circom-helper/build/utils.js:5:58)

  ● ProcessMessage circuit › 1 user, key-change › should produce the correct state root and ballot root

    Wrong number of inputs

      at node_modules/circom-helper/ts/utils.ts:34:15
      at step (node_modules/circom-helper/build/utils.js:33:23)
      at Object.next (node_modules/circom-helper/build/utils.js:14:53)
      at fulfilled (node_modules/circom-helper/build/utils.js:5:58)

  ● ProcessMessage circuit › 1 user, 10 messages › should produce the correct state root and ballot root

    Wrong number of inputs

      at node_modules/circom-helper/ts/utils.ts:34:15
      at step (node_modules/circom-helper/build/utils.js:33:23)
      at Object.next (node_modules/circom-helper/build/utils.js:14:53)
      at fulfilled (node_modules/circom-helper/build/utils.js:5:58)

Test Suites: 1 failed, 1 total
Tests:       4 failed, 4 total
Snapshots:   0 total
Time:        10.441 s, estimated 79 s
Ran all test suites matching /ts\/__tests__\/ProcessMessages.test.ts/i.
  console.log
    {
      pollEndTimestamp: '1667311246',
      packedVals: '12845229234353645267777574866193589610867589145',
      msgRoot: '5760018142955712083860948735390574278049156836055787353706212948788736729987',
      msgs: [
        [
          '1',
          '13837359783826108306989060253395981510188032687592787023696265829538067158643',
          '19987926470278825092855928537107071096579117000804911799371589634809891285641',
          '10654773698875189527513838147547217586657316803350531940589750325993082112672',
          '1772084879939409814130243963525781746836498876764007322142970872763041497858',
          '20471451123206773454823143340626335402655905631442055926297570671639325769085',
          '13337084512306283812364394796498475225793208178944707203660113988641211728325',
          '17292913338574344110917635115533739721313245558762195052590732425163990888823',
          '8036798861759211094606107964907347001368806422455623113977019795577591738849',
          '13272538130624642722306543170692154514722402972163133643123701458219464092754',
          '14390717632638424374320268373360561643183859019062019152341922228685244280084'
        ],
        [
          '1',
          '8906648667498986075511191892878139021444376548012931593235705303268844363659',
          '10193815803880077576354382367028763607358018936497069326380922310940115059066',
          '2890609090612987465504760867942626219030843750785717608206473215450224669990',
          '11992339201058806195344641160705375361506164968402902980118141945576053807199',
          '21283394334700848924943611450316076720833784492273167743543230900782006752077',
          '16728016418177875762567591022915918845817103708998330757099157836443752763179',
          '7295985308997405405064287100360845980980103930119524015260704929555347075287',
          '16560649496375544901129346781237107543441285071520810897723862889058038468415',
          '6549416242730972889199147428574824080999445003016253084093316867421728656865',
          '18619627042206352736452024513911784906699964261738753567351050165124038878501'
        ],
        [
          '1',
          '19079067900319528500265765066830502988513866107783699858271194647214006225619',
          '11275710143013496762190569267625565356296877977002618169664820870269415132121',
          '18416338522247555198825627259501975197706618822233680173279216127437096827780',
          '8061824098153147644245586365718706466355814813295530955571514122397015047682',
          '19072007166127863008643540825866573988548558853560449709486850209990391573148',
          '13602392701398850116409942846154099923449314659300823033513238982125921754340',
          '7842011665700821154664724575884151065010331350912482162528820367021526673347',
          '21382534232795398289272964038686495789482995794846300753141911119866987915915',
          '10864730937140782570862982227598332106483222029467791584481560336015173034732',
          '6485219144985773937027623551702819226771134639608384442286217850832016590931'
        ],
        [
          '1',
          '17464310365207748512073548812334658279485451336338158288796981756820242500722',
          '20435704024953801397570537204841595751841442455501324899388602657969997536797',
          '15592064023951737657974947870102834355083903998877486859365096491206694314866',
          '21413172592617077369400382828890219802918668216956632228248062295659901398147',
          '18484942374396916513406708270836618622841695049817153540506457974886857404079',
          '3784381253768140110411912244805797793036104029979728971258646544618604406742',
          '4764851783745035792603527187702582794741628688996978609595071559030289880378',
          '9867033585916793520081145561119600750532265800638659990964758140276049761862',
          '8148045745268316046676235991966358184670377785164926860187120229342285251050',
          '5134802525168375711079932185072673709821244104852906911826116290227357940964'
        ],
        [
          '1',
          '17464310365207748512073548812334658279485451336338158288796981756820242500722',
          '20435704024953801397570537204841595751841442455501324899388602657969997536797',
          '15592064023951737657974947870102834355083903998877486859365096491206694314866',
          '21413172592617077369400382828890219802918668216956632228248062295659901398147',
          '18484942374396916513406708270836618622841695049817153540506457974886857404079',
          '3784381253768140110411912244805797793036104029979728971258646544618604406742',
          '4764851783745035792603527187702582794741628688996978609595071559030289880378',
          '9867033585916793520081145561119600750532265800638659990964758140276049761862',
          '8148045745268316046676235991966358184670377785164926860187120229342285251050',
          '5134802525168375711079932185072673709821244104852906911826116290227357940964'
        ]
      ],
      msgSubrootPathElements: [
        [
          '6992668053315860700147460697507918392937953240225162891595498395786481768940',
          '12915444503621073454579416579430905206970714557680052030066757042249102605307',
          '12915444503621073454579416579430905206970714557680052030066757042249102605307',
          '12915444503621073454579416579430905206970714557680052030066757042249102605307'
        ]
      ],
      coordPrivKey: '5658374270239247761384679152233201121059904416820998063722200996131697405357',
      coordPubKey: [
        '11332497698758354019035865474675813084220127271789735893271766537626571423476',
        '20431691625855534865175910058830939474109498190752912725628632517332015186311'
      ],
      encPubKeys: [
        [
          '6403400650728418481711409980083146479903632089042510003594990170931334722732',
          '21104801033951054406049962952825006221926675169001416052647623718824179051820'
        ],
        [
          '18390630056874033301451608885785905030949135024400418333352446444481582023164',
          '4525804328899520904377579932796327425406365344756868538638900465255841433378'
        ],
        [
          '8678212706852428410433609983451443917300561132345600258177149330322348217332',
          '19579475263645810878680287422625636051632580320484733642382903742028163489898'
        ],
        [
          '15914849107842169791490404487862923872467587707512986546252407248140085356005',
          '12844009287167889379992401857503494903128595027525809772643249410991163876298'
        ],
        [
          '15914849107842169791490404487862923872467587707512986546252407248140085356005',
          '12844009287167889379992401857503494903128595027525809772643249410991163876298'
        ]
      ],
      currentStateRoot: '8629138558045575311123840329193490322824627160607454348892688866790292151148',
      currentBallotRoot: '9105453741665960449792281626882014222103501499246287334255160659262747058842',
      currentSbCommitment: '9481510522105360387544393632840784997238123937600910789419303303362558784408',
      currentSbSalt: '0',
      currentStateLeaves: [
        [
          '19116292823119193370867447745716321234777874467146566269445073993540999275772',
          '14488075390366710293149828702296896277055662957207054281984995932627071436409',
          '97',
          '1667311216'
        ],
        [
          '19116292823119193370867447745716321234777874467146566269445073993540999275772',
          '14488075390366710293149828702296896277055662957207054281984995932627071436409',
          '98',
          '1667311216'
        ],
        [
          '19116292823119193370867447745716321234777874467146566269445073993540999275772',
          '14488075390366710293149828702296896277055662957207054281984995932627071436409',
          '99',
          '1667311216'
        ],
        [
          '19116292823119193370867447745716321234777874467146566269445073993540999275772',
          '14488075390366710293149828702296896277055662957207054281984995932627071436409',
          '100',
          '1667311216'
        ],
        [
          '10457101036533406547632367118273992217979173478358440826365724437999023779287',
          '19824078218392094440610104313265183977899662750282163392862422243483260492317',
          '0',
          '0'
        ]
      ],
      currentStateLeavesPathElements: [
        [
          [Array], [Array],
          [Array], [Array],
          [Array], [Array],
          [Array], [Array],
          [Array], [Array]
        ],
        [
          [Array], [Array],
          [Array], [Array],
          [Array], [Array],
          [Array], [Array],
          [Array], [Array]
        ],
        [
          [Array], [Array],
          [Array], [Array],
          [Array], [Array],
          [Array], [Array],
          [Array], [Array]
        ],
        [
          [Array], [Array],
          [Array], [Array],
          [Array], [Array],
          [Array], [Array],
          [Array], [Array]
        ],
        [
          [Array], [Array],
          [Array], [Array],
          [Array], [Array],
          [Array], [Array],
          [Array], [Array]
        ]
      ],
      currentBallots: [
        [
          '3',
          '9609821260045808147761438232754775920383745724373586166426358681485206124272'
        ],
        [
          '2',
          '10130561671535557442963660514947189294294498597124481326368569617465202941168'
        ],
        [
          '1',
          '9525772251731073024154700171374895293085392048729017481098619397950413685292'
        ],
        [
          '0',
          '19261153649140605024552417994922546473530072875902678653210025980873274131905'
        ],
        [
          '0',
          '19261153649140605024552417994922546473530072875902678653210025980873274131905'
        ]
      ],
      currentBallotsPathElements: [
        [
          [Array], [Array],
          [Array], [Array],
          [Array], [Array],
          [Array], [Array],
          [Array], [Array]
        ],
        [
          [Array], [Array],
          [Array], [Array],
          [Array], [Array],
          [Array], [Array],
          [Array], [Array]
        ],
        [
          [Array], [Array],
          [Array], [Array],
          [Array], [Array],
          [Array], [Array],
          [Array], [Array]
        ],
        [
          [Array], [Array],
          [Array], [Array],
          [Array], [Array],
          [Array], [Array],
          [Array], [Array]
        ],
        [
          [Array], [Array],
          [Array], [Array],
          [Array], [Array],
          [Array], [Array],
          [Array], [Array]
        ]
      ],
      currentVoteWeights: [ '0', '0', '0', '0', '0' ],
      currentVoteWeightsPathElements: [
        [ [Array], [Array] ],
        [ [Array], [Array] ],
        [ [Array], [Array] ],
        [ [Array], [Array] ],
        [ [Array], [Array] ]
      ],
      newSbSalt: '17265535501474261965159048080561165380827356357564820939444687231395589775157',
      newSbCommitment: '5056380872657529225604542709332361837858960386136467162298758755374570475557',
      inputHash: '5489297672808883267567987950718286714067072261466465675344350886610014071504'
    }

      at ts/__tests__/ProcessMessages.test.ts:558:25

  console.log
    processMessages_test

      at ts/__tests__/ProcessMessages.test.ts:559:25
```

It could be reproduced by pulling 2789ae65c6e039ee1d177f9358e52f0a2e9e386c of PR #522.

**Comment by chaosma** [comment]
after rebuilt everything, seems problem solved

**Comment by gurrpi** [comment]
Should re-run `npm run bootstrap` on project root directory when the linking between sub-packages has been released (e.g. executed `npm install` command in `circuit` package. NPM will fetch remote version rather than associated local package).

**Comment by gurrpi** [comment]
Figured out 6f1fa85299ebbc8fe10e30691afe8f036b8c68d1 has introduced test failure on `circuits` package:

```
● ProcessMessage circuit › 1 user, 2 messages › should produce the correct state root and ballot root

    expect(received).toEqual(expected) // deep equality

    Expected: "15169122095827655333057219979024055999470295255698127248874602703460386380809"
    Received: "2911853043637406563688121497339426948955531659810611109634353783360722441820"

      165 |
      166 |             expect(messageTree.root.toString())
    > 167 |                 .toEqual(
          |                  ^
      168 |                     poll.messageAq.getRoot(
      169 |                         treeDepths.messageTreeDepth,
      170 |                     ).toString()

      at ts/__tests__/ProcessMessages.test.ts:167:18
      at step (ts/__tests__/ProcessMessages.test.ts:33:23)
      at Object.next (ts/__tests__/ProcessMessages.test.ts:14:53)
      at ts/__tests__/ProcessMessages.test.ts:8:71
      at Object.<anonymous>.__awaiter (ts/__tests__/ProcessMessages.test.ts:4:12)
      at Object.<anonymous> (ts/__tests__/ProcessMessages.test.ts:85:19)

  ● ProcessMessage circuit › 1 user, 2 messages › should produce the correct state root and ballot root

    assert(received)

    Expected value to be equal to:
      true
    Received:
      false

      292 |
      293 |         // Require that the message queue has been merged
    > 294 |         assert(this.isMessageAqMerged())
          |         ^
      295 |         assert(this.messageAq.hasRoot(this.treeDepths.messageTreeDepth))
      296 |
      297 |         const batchSize = this.batchSizes.messageBatchSize

      at Poll.processMessages (../core/ts/MaciState.ts:294:9)
      at ts/__tests__/ProcessMessages.test.ts:194:42
      at step (ts/__tests__/ProcessMessages.test.ts:33:23)
      at Object.next (ts/__tests__/ProcessMessages.test.ts:14:53)
      at ts/__tests__/ProcessMessages.test.ts:8:71
      at Object.<anonymous>.__awaiter (ts/__tests__/ProcessMessages.test.ts:4:12)
      at Object.<anonymous> (ts/__tests__/ProcessMessages.test.ts:174:69)
```

### 8300cc548e954a80ab6fb39ab9d559c999e07c10

```
npm run test-processMessages

> maci-circuits@1.1.0 test-processMessages
> NODE_OPTIONS=--max-old-space-size=4096 jest ts/__tests__/ProcessMessages.test.ts

  console.log
    Signing up with 14434780084084022819484116535012917159963211897268354077703959798202097973505n

      at ts/__tests__/ProcessMessages.test.ts:380:21

 FAIL  ts/__tests__/ProcessMessages.test.ts (10.589 s)
  ProcessMessage circuit
    1 user, 2 messages
      ✕ should produce the correct state root and ballot root (1062 ms)
    2 users, 1 message
      ✕ should produce the correct state root and ballot root (786 ms)
    1 user, key-change
      ✕ should produce the correct state root and ballot root (1132 ms)
    1 user, 10 messages
      ✕ should produce the correct state root and ballot root (3850 ms)

  ● ProcessMessage circuit › 1 user, 2 messages › should produce the correct state root and ballot root

    expect(received).toEqual(expected) // deep equality

    Expected: "21183548314755890092395196197919847185435093806345683813583675792343266193680"
    Received: "2821152164900325317316112876991970539865644369352123125365646208216523249812"

      165 |
      166 |             expect(messageTree.root.toString())
    > 167 |                 .toEqual(
          |                  ^
      168 |                     poll.messageAq.getRoot(
      169 |                         treeDepths.messageTreeDepth,
      170 |                     ).toString()

      at ts/__tests__/ProcessMessages.test.ts:167:18
      at step (ts/__tests__/ProcessMessages.test.ts:33:23)
      at Object.next (ts/__tests__/ProcessMessages.test.ts:14:53)
      at ts/__tests__/ProcessMessages.test.ts:8:71
      at Object.<anonymous>.__awaiter (ts/__tests__/ProcessMessages.test.ts:4:12)
      at Object.<anonymous> (ts/__tests__/ProcessMessages.test.ts:85:19)

  ● ProcessMessage circuit › 1 user, 2 messages › should produce the correct state root and ballot root

    Error: processMessages_test: processMessages_test.cpp:475197: void QuinLeafExists_341_run(uint, Circom_CalcWit*): Assertion `Fr_isTrue(&expaux[0])' failed.
    Aborted (core dumped)

      at node_modules/circom-helper/ts/utils.ts:34:15
      at step (node_modules/circom-helper/build/utils.js:33:23)
      at Object.next (node_modules/circom-helper/build/utils.js:14:53)
      at fulfilled (node_modules/circom-helper/build/utils.js:5:58)

  ● ProcessMessage circuit › 2 users, 1 message › should produce the correct state root and ballot root

    expect(received).toEqual(expected) // deep equality

    Expected: "6924662005720968488421320339791945895797907758779413248795137275765560276855"
    Received: "473203688706261366500525519770515691349464485050179243673982777459147213168"

      314 |
      315 |             expect(messageTree.root.toString())
    > 316 |                 .toEqual(
          |                  ^
      317 |                     poll.messageAq.getRoot(
      318 |                         treeDepths.messageTreeDepth,
      319 |                     ).toString()

      at ts/__tests__/ProcessMessages.test.ts:316:18
      at step (ts/__tests__/ProcessMessages.test.ts:33:23)
      at Object.next (ts/__tests__/ProcessMessages.test.ts:14:53)
      at ts/__tests__/ProcessMessages.test.ts:8:71
      at Object.<anonymous>.__awaiter (ts/__tests__/ProcessMessages.test.ts:4:12)
      at Object.<anonymous> (ts/__tests__/ProcessMessages.test.ts:250:19)

  ● ProcessMessage circuit › 2 users, 1 message › should produce the correct state root and ballot root

    Error: processMessages_test: processMessages_test.cpp:475197: void QuinLeafExists_341_run(uint, Circom_CalcWit*): Assertion `Fr_isTrue(&expaux[0])' failed.
    Aborted (core dumped)

      at node_modules/circom-helper/ts/utils.ts:34:15
      at step (node_modules/circom-helper/build/utils.js:33:23)
      at Object.next (node_modules/circom-helper/build/utils.js:14:53)
      at fulfilled (node_modules/circom-helper/build/utils.js:5:58)

  ● ProcessMessage circuit › 1 user, key-change › should produce the correct state root and ballot root

    expect(received).toEqual(expected) // deep equality

    Expected: "13387025291565465358705381861383273763789857513351792951639739013156366321316"
    Received: "15726676152682740942286626010559917712403185255465353376216395577592930785610"

      479 |
      480 |             expect(messageTree.root.toString())
    > 481 |                 .toEqual(
          |                  ^
      482 |                     poll.messageAq.getRoot(
      483 |                         treeDepths.messageTreeDepth,
      484 |                     ).toString()

      at ts/__tests__/ProcessMessages.test.ts:481:18
      at step (ts/__tests__/ProcessMessages.test.ts:33:23)
      at Object.next (ts/__tests__/ProcessMessages.test.ts:14:53)
      at ts/__tests__/ProcessMessages.test.ts:8:71
      at Object.<anonymous>.__awaiter (ts/__tests__/ProcessMessages.test.ts:4:12)
      at Object.<anonymous> (ts/__tests__/ProcessMessages.test.ts:370:19)

  ● ProcessMessage circuit › 1 user, key-change › should produce the correct state root and ballot root

    Error: processMessages_test: processMessages_test.cpp:475197: void QuinLeafExists_341_run(uint, Circom_CalcWit*): Assertion `Fr_isTrue(&expaux[0])' failed.
    Aborted (core dumped)

      at node_modules/circom-helper/ts/utils.ts:34:15
      at step (node_modules/circom-helper/build/utils.js:33:23)
      at Object.next (node_modules/circom-helper/build/utils.js:14:53)
      at fulfilled (node_modules/circom-helper/build/utils.js:5:58)

  ● ProcessMessage circuit › 1 user, 10 messages › should produce the correct state root and ballot root

    Error: processMessages_test: processMessages_test.cpp:475197: void QuinLeafExists_341_run(uint, Circom_CalcWit*): Assertion `Fr_isTrue(&expaux[0])' failed.
    Aborted (core dumped)

      at node_modules/circom-helper/ts/utils.ts:34:15
      at step (node_modules/circom-helper/build/utils.js:33:23)
      at Object.next (node_modules/circom-helper/build/utils.js:14:53)
      at fulfilled (node_modules/circom-helper/build/utils.js:5:58)

Test Suites: 1 failed, 1 total
Tests:       4 failed, 4 total
Snapshots:   0 total
Time:        10.621 s
Ran all test suites matching /ts\/__tests__\/ProcessMessages.test.ts/i.
```

**Comment by ctrlc03** [comment]
Last commit: https://github.com/privacy-scaling-explorations/maci/pull/522/commits/506731098dc6929c51244b5731dcc3a2c1265264
Error: https://github.com/privacy-scaling-explorations/maci/blob/506731098dc6929c51244b5731dcc3a2c1265264/circuits/circom/processMessages.circom#L185
MaciState: https://github.com/privacy-scaling-explorations/maci/blob/506731098dc6929c51244b5731dcc3a2c1265264/core/ts/MaciState.ts#L142 and https://github.com/privacy-scaling-explorations/maci/blob/506731098dc6929c51244b5731dcc3a2c1265264/core/ts/MaciState.ts#L143

Removing those two lines makes the circuit work, however the rest will fail.

**Comment by chaosma** [comment]
The issue is solved: https://github.com/ctrlc03/maci/pull/2

The reason is that we should use contract to mandatorily insert NOTHING_UP_MY_SLEEVE leaf. And the MaciCore.ts will automatically parse every message including this one. It means we don't have to do adding this leaf manually in MaciCore.ts

With this change, the unit tests passed as well as end to end test. Otherwise, both unit test and end to end test will fail

**Comment by ctrlc03** [comment]
Fixed: https://github.com/privacy-scaling-explorations/maci/pull/522/commits/51e84f81b13cd6fd56dbbb2887f541f273cd1313
