### ISSUE TITLE
Cannot build zksnarks

### ISSUE THREAD

**Issue by brendanww** [privacy-scaling-explorations/maci#546]
Due to https://github.com/nodejs/node/issues/40774 it's not possible to follow this section of setup instructions

<img width="921" alt="image" src="https://user-images.githubusercontent.com/65564422/203172928-ff35f689-376b-4f8b-aa88-19609151ed17.png">

I'll add a PR to update README once I've found a way to troubleshoot, and ideally add a .nvmrc to remove node version ambiguity

**Comment by brendanww** [comment]
Seeing this error also when using container built from the top-level dockerfile:

```
> ./scripts/buildBatchUpdateStateTreeSnark.sh

Error: illegal value for flag --max-old-space-size=null of type size_t
Try --help for options
/root/.nvm/versions/node/v12.18.1/bin/node: bad option: --max-old-space-size=null
Error: exec:
    at Object.error (/maci/circuits/node_modules/shelljs/src/common.js:110:27)
    at execSync (/maci/circuits/node_modules/shelljs/src/exec.js:120:12)
    at Object._exec (/maci/circuits/node_modules/shelljs/src/exec.js:223:12)
    at Object.exec (/maci/circuits/node_modules/shelljs/src/common.js:335:23)
    at main (/maci/circuits/build/buildSnarks.js:102:11)
    at Object.<anonymous> (/maci/circuits/build/buildSnarks.js:143:20)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
```

**Comment by brendanww** [comment]
Actually, looks like this is an issue with `buildBatchUpdateStateTreeSnark.sh` which runs `build/buildSnarks.js` 

`buildSnarks.js` expects an `-ml` or `--memory-limit` argument but that argument is not passed in by `buildBatchUpdateStateTreeSnark.sh`

this can be fixed by updating `buildBatchUpdateStateTreeSnark.sh` to pass `-ml 8192`

**Comment by gurrpi** [comment]
Please note that MACI v0.9.x of `master` branch would be deprecated soon. Check MACI [v1](https://github.com/privacy-scaling-explorations/maci/tree/v1) to use latest feature (see [A Technical Introduction to MACI 1.0](https://mirror.xyz/privacy-scaling-explorations.eth/IlWP_ITvmeZ2-elTJl44SCEGlBiemKt3uxXv2A6Dqy4) for more detail).
